import type { ChampListEntry } from './ChampObj';
// prettier-ignore
export type ChampionName = "Annie";

export const ChampionListData = {
  Annie: {
    name: 'Annie',
    image: {
      full: 'Annie.png',
      sprite: 'champion0.png',
      group: 'champion',
      x: 336,
      y: 0,
      w: 48,
      h: 48,
    },
    id: 1,
    apiname: 'Annie',
    title: 'the Dark Child',
    attack: 2,
    defense: 3,
    magic: 10,
    difficulty: 1,
    herotype: 'Mage',
    alttype: '',
    resource: 'Mana',
    stats: {
      hp_base: 560,
      hp_lvl: 102,
      mp_base: 418,
      mp_lvl: 25,
      arm_base: 19,
      arm_lvl: 4.7,
      mr_base: 30,
      mr_lvl: 1.3,
      hp5_base: 5.5,
      hp5_lvl: 0.55,
      mp5_base: 8,
      mp5_lvl: 0.8,
      dam_base: 50,
      dam_lvl: 2.65,
      as_base: 0.579,
      as_ratio: 0.578999996185302,
      as_lvl: 1.36,
      missile_speed: 1200,
      attack_cast_time: 0,
      attack_total_time: 0,
      attack_delay_offset: -0.10420524328947,
      windup_modifier: 0,
      crit_base: 175,
      crit_mod: 0,
      range: 625,
      ms: 335,
      gameplay_radius: 55,
      acquisition_radius: 625,
      selection_radius: 100,
      pathing_radius: 30,
      urf: {
        dmg_dealt: 0.9,
        dmg_taken: 1,
      },
    },
    rangetype: 'Ranged',
    date: '2009-02-21',
    patch: 'Alpha Week 2',
    changes: 'V13.3',
    role: ['Burst'],
    positions: ['Middle'],
    op_positions: ['Middle'],
    damage: 3,
    toughness: 1,
    control: 3,
    mobility: 1,
    utility: 2,
    style: 100,
    adaptivetype: 'Magic',
    be: 450,
    rp: 260,
    skill_i: ['Pyromania'],
    skill_q: ['Disintegrate'],
    skill_w: ['Incinerate'],
    skill_e: ['Molten Shield'],
    skill_r: ['Summon: Tibbers', 'Command: Tibbers'],
    skills: [
      'Pyromania',
      'Disintegrate',
      'Incinerate',
      'Molten Shield',
      'Summon: Tibbers',
    ],
    fullname: 'Annie Hastur',
    nickname: '',
    secondary_attributes: '',
  },
} satisfies Record<ChampionName, ChampListEntry>;

export default ChampionListData;
