import type { SubSkill } from '@/api/DataTypes';
import type { ChampionName } from '../ChampionListData';
import ChampionListData from '../ChampionListData';
export const name: ChampionName = 'Udyr';
const I: SubSkill[] = [
  {
    img: '/wiki/images/Udyr_Bridge_Between.png',
    description:
      '<span class="template_sbc"><b>Innate - Awakened Spirit:</b></span> <b>Udyr</b> has no <a href="/wiki/Champion_ability" title="Champion ability">ultimate ability</a> and instead has 4 <a href="/wiki/Champion_ability" title="Champion ability">basic abilities</a> that each incur a <span style="white-space:nowrap"><a href="/wiki/Cooldown" title="Cooldown"><img alt="Cooldown icon.png" src="/wiki/images/Cooldown_icon.png" decoding="async" loading="lazy" width="15" height="15" class="lazyload"></a>&nbsp;<span class="basic-tooltip" style="border-bottom:1px dotted gray;cursor:help;" title="Affected by ability haste">1.<small>5</small>-second global cooldown</span></span> when cast. Each ability grants a <i>Stance</i> that empowers his next two basic attacks, and switching <i>Stances</i> will replace the empowered attacks from the previous <i>Stance</i>.',
    leveling: [],
  },
  {
    description:
      'Periodically, after <b>Udyr</b> enters a <i>Stance</i>, he can cast it again at no cost after 0.<small>25</small> seconds to <i>Awaken</i> it, refreshing the cooldown and empowering the <i>Stance</i> with an additional effect.<br>This effect is placed on cooldown at the start of the game.',
    leveling: [],
  },
  {
    img: '/wiki/images/Udyr_Bridge_Between_2.png',
    description:
      '<span class="template_sbc"><b>Innate - Monk Training:</b></span> After casting an ability, <b>Udyr</b> empowers his next two <a href="/wiki/Basic_attack" title="Basic attack">basic attacks</a> within 4 seconds to gain <span style="white-space:nowrap"><a href="/wiki/Attack_speed" title="Attack speed"><img alt="Attack speed icon.png" src="/wiki/images/Attack_speed_icon.png" decoding="async" loading="lazy" width="15" height="15" class="lazyload"></a>&nbsp;<span style="color:orangered; white-space:normal">30% <b>bonus</b> attack speed</span></span> and refund 5% of <i>Awakened Spirit\'s</i> <b>total</b> cooldown, though not if the remaining cooldown is less than 1 second.',
    leveling: [],
  },
];
const Q: SubSkill[] = [
  {
    img: '/wiki/images/Udyr_Wilding_Claw.png',
    description:
      '<span class="template_sbc"><b>Active - Stance:</b></span> <b>Udyr</b> enters <i>Claw Stance</i>, empowering his next two basic attacks to gain <span style="white-space:nowrap"><a href="/wiki/Range" title="Range"><img alt="Range icon.png" src="/wiki/images/Range_icon.png" decoding="async" loading="lazy" width="15" height="15" class="lazyload"></a>&nbsp;50</span> <b>bonus</b> range and deal <span style="color: #FF8C34; white-space:normal"><b>bonus</b> physical damage</span>.',
    leveling: [
      {
        effectType: 'Heal',
        name: 'Bonus Physical Damage:',
        raw: "3 / 4 / 5 / 6 / 7 / 8% (+ 4% per 100 bonus AD) of target's maximum health",
        healType: 'OutgoingHeals',
        values: [3, 4, 5, 6, 7, 8],
        valuesIsPercent: true,
        user: 'target',
        units: 'maximum_hp',
        unitsText: "of target's maximum health",
        pre: '3 / 4 / 5 / 6 / 7 / 8%',
        post: "of target's maximum health",
        children: [
          {
            values: 4,
            valuesIsPercent: true,
            user: 'player',
            units: 'bonus_ad',
            unitsText: 'per 100 bonus AD',
            pre: '+ 4% per 100 bonus AD',
          },
        ],
      },
      {
        effectType: 'Heal',
        name: 'Total Physical Damage:',
        raw: "6 / 8 / 10 / 12 / 14 / 16% (+ 8% per 100 bonus AD) of target's maximum health",
        healType: 'OutgoingHeals',
        values: [6, 8, 10, 12, 14, 16],
        valuesIsPercent: true,
        user: 'target',
        units: 'maximum_hp',
        unitsText: "of target's maximum health",
        pre: '6 / 8 / 10 / 12 / 14 / 16%',
        post: "of target's maximum health",
        children: [
          {
            values: 8,
            valuesIsPercent: true,
            user: 'player',
            units: 'bonus_ad',
            unitsText: 'per 100 bonus AD',
            pre: '+ 8% per 100 bonus AD',
          },
        ],
      },
    ],
  },
  {
    description:
      'Additionally, <b>Udyr</b> gains <span style="color:orangered; white-space:normal"><b>bonus</b> attack speed</span> and deals <span style="color: #FF8C34; white-space:normal"><b>bonus</b> physical damage</span> <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="On-hit"><a href="/wiki/Attack_effects#On_Hitting" title="Attack effects#On Hitting"><img alt="On-hit icon.png" src="/wiki/images/On-hit_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Attack_effects#On_Hitting" title="Attack effects">on-hit</a></span> for 4 seconds.',
    leveling: [
      {
        effectType: 'Unique',
        name: 'Bonus Attack Speed:',
        raw: '20 / 32 / 44 / 56 / 68 / 80%',
        values: [20, 32, 44, 56, 68, 80],
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '20 / 32 / 44 / 56 / 68 / 80%',
      },
      {
        effectType: 'Unique',
        name: 'Bonus Physical Damage On-Hit:',
        raw: '5 / 11 / 17 / 23 / 29 / 35 (+ 30% bonus AD)',
        values: [5, 11, 17, 23, 29, 35],
        user: 'none',
        units: '',
        unitsText: '',
        pre: '5 / 11 / 17 / 23 / 29 / 35',
        children: [
          {
            values: 30,
            valuesIsPercent: true,
            user: 'player',
            units: 'bonus_ad',
            unitsText: 'bonus AD',
            pre: '+ 30% bonus AD',
          },
        ],
      },
    ],
  },
  {
    description:
      '<span class="template_sbc"><b>Recast - Awaken:</b></span> <b>Udyr</b> gains an additional <span style="color:orangered; white-space:normal"><span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="20;" data-finish="70;" data-bot_values="20;22.94;25.88;28.82;31.76;34.71;37.65;40.59;43.53;46.47;49.41;52.35;55.29;58.24;61.18;64.12;67.06;70" data-top_values="" data-bot_key="%">20% − 70% (based on level)</span> <b>bonus</b> attack speed</span>. The empowered attacks deal an additional <span style="color: #1F995C; white-space:normal"><span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="2;" data-finish="4;" data-bot_values="2;2.12;2.24;2.35;2.47;2.59;2.71;2.82;2.94;3.06;3.18;3.29;3.41;3.53;3.65;3.76;3.88;4" data-top_values="" data-bot_key="%">2% − 4% (based on level)</span> <span style="color:orange; white-space:normal">(+&nbsp;2% per 100 <b>bonus</b> AD)</span> of target\'s <b>maximum</b> health</span> <a href="/wiki/Critical_strike#Cosmetic_critical_strikes" title="Critical strike#Cosmetic critical strikes"><img alt="Critical strike physical icon.png" src="/wiki/images/Critical_strike_physical_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <span class="basic-tooltip" style="border-bottom:1px dotted gray;cursor:help;" title="Cosmetic critical strike"><span style="color: #FF8C34; white-space:normal"><b>bonus</b> physical damage</span></span>. <b>Udyr\'s</b> next two basic attacks in any <i>Stance</i> are empowered to strike with lightning 6 times, dealing <a href="/wiki/Critical_strike#Cosmetic_critical_strikes" title="Critical strike#Cosmetic critical strikes"><img alt="Critical strike magic icon.png" src="/wiki/images/Critical_strike_magic_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <span class="basic-tooltip" style="border-bottom:1px dotted gray;cursor:help;" title="Cosmetic critical strike"><span style="color: #00B0F0; white-space:normal"><b>bonus</b> magic damage</span></span> equal to <span style="color: #1F995C; white-space:normal"><span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="1.5;" data-finish="3;" data-bot_values="1.5;1.59;1.68;1.76;1.85;1.94;2.03;2.12;2.21;2.29;2.38;2.47;2.56;2.65;2.74;2.82;2.91;3" data-top_values="" data-bot_key="%">1.<small>5</small>% − 3% (based on level)</span></span> <span style="color: #7A6DFF; white-space:normal">(+&nbsp;0.<small>8</small>% per 100 AP)</span> <span style="color: #1F995C; white-space:normal">of the target\'s <b>maximum</b> health</span> per hit, chaining to up to 3 nearby <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Sight"><a href="/wiki/Sight" title="Sight"><img alt="Sight icon.png" src="/wiki/images/Sight_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Sight" title="Sight">visible</a></span> enemies and being able to hit the same target multiple times. This deals a minumum of <span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="40;" data-finish="160;" data-bot_values="40;47.06;54.12;61.18;68.24;75.29;82.35;89.41;96.47;103.53;110.59;117.65;124.71;131.76;138.82;145.88;152.94;160" data-top_values="">40 − 160 (based on level)</span> against <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Minions"><a href="/wiki/Minion_(League_of_Legends)" title="Minion (League of Legends)"><img alt="Minion icon.png" src="/wiki/images/Minion_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Minion_(League_of_Legends)" title="Minion (League of Legends)">minions</a></span> and is capped at 20 <span style="color:orange; white-space:normal">(+&nbsp;100% <b>bonus</b> AD)</span> <span style="color: #7A6DFF; white-space:normal">(+&nbsp;50% AP)</span> against <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Monster"><a href="/wiki/Monster" title="Monster"><img alt="Monster icon.png" src="/wiki/images/Monster_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Monster" title="Monster">monsters</a></span>.',
    leveling: [
      {
        effectType: 'Gain',
        name: 'Line 1:',
        raw: ' Udyr gains an additional 20% − 70% (based on level) bonus attack speed',
        increasedStat: 'bonus_ad',
        values: [],
        valuesIsPercent: true,
        valuesIsBasedOnLevel: true,
        user: 'player',
        units: '',
        unitsText: 'bonus attack speed',
        pre: 'Udyr gains an additional 20% − 70%',
        post: 'bonus attack speed',
      },
      {
        effectType: 'Heal',
        name: 'Line 2:',
        raw: " The empowered attacks deal an additional 2% − 4% (based on level) (+ 2% per 100 bonus AD) of target's maximum health  bonus physical damage",
        healType: 'PhysicalVamp',
        values: [],
        valuesIsPercent: true,
        valuesIsBasedOnLevel: true,
        user: 'target',
        units: 'maximum_hp',
        unitsText: "of target's maximum health  bonus physical damage",
        pre: 'The empowered attacks deal an additional 2% − 4%',
        post: "of target's maximum health  bonus physical damage",
        children: [
          {
            values: 2,
            valuesIsPercent: true,
            user: 'player',
            units: 'bonus_ad',
            unitsText: 'per 100 bonus AD',
            pre: '+ 2% per 100 bonus AD',
          },
        ],
      },
      {
        effectType: 'Unique',
        name: 'Line 4:',
        raw: '5% − 3% (based on level) (+ 0',
        values: [],
        valuesIsPercent: true,
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: '+ 0',
        pre: '5% − 3%',
        post: '+ 0',
      },
      {
        effectType: 'Gain',
        name: 'Line 6:',
        raw: ' This deals a minumum of 40 − 160 (based on level) against  minions and is capped at 20 (+ 100% bonus AD) (+ 50% AP) against  monsters',
        increasedStat: 'total_ap',
        values: [
          40, 47.06, 54.12, 61.18, 68.24, 75.29, 82.35, 89.41, 96.47, 103.53,
          110.59, 117.65, 124.71, 131.76, 138.82, 145.88, 152.94, 160,
        ],
        valuesIsBasedOnLevel: true,
        user: 'player',
        units: '',
        unitsText: 'against  minions and is capped at 20',
        pre: 'This deals a minumum of 40 − 160',
        post: 'against  minions and is capped at 20',
        children: [
          {
            values: 100,
            valuesIsPercent: true,
            user: 'player',
            units: 'bonus_ad',
            unitsText: 'bonus AD',
            pre: '+ 100% bonus AD',
          },
          {
            values: 50,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 50% AP',
          },
        ],
      },
    ],
  },
];
const W: SubSkill[] = [
  {
    img: '/wiki/images/Udyr_Iron_Mantle.png',
    description:
      '<span class="template_sbc"><b>Active - Stance:</b></span> <b>Udyr</b> enters <i>Mantle Stance</i>, empowering his next two basic attacks to gain <span style="white-space:nowrap"><a href="/wiki/Life_steal" title="Life steal"><img alt="Life steal icon.png" src="/wiki/images/Life_steal_icon.png" decoding="async" loading="lazy" width="15" height="15" class="lazyload"></a>&nbsp;<a href="/wiki/Life_steal" title="Life steal">life steal</a></span> and <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Heal"><a href="/wiki/Healing" title="Healing"><img alt="Heal power icon.png" src="/wiki/images/Heal_power_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Healing" title="Healing">heal</a></span> him for <span style="color: #1F995C; white-space:normal">1.<small>2</small>% of his <b>maximum</b> health</span> <span style="color: #7A6DFF; white-space:normal">(+&nbsp;8% AP)</span> on-hit.',
    leveling: [
      {
        effectType: 'Heal',
        name: 'Line 2:',
        raw: '2% of his maximum health (+ 8% AP) on-hit',
        healType: 'BonusHealth',
        values: 2,
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: 'on-hit',
        pre: '2% of his maximum health',
        post: 'on-hit',
        children: [
          {
            values: 8,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 8% AP',
          },
        ],
      },
      {
        effectType: 'Unique',
        name: 'Life Steal:',
        raw: '15 / 16 / 17 / 18 / 19 / 20%',
        values: [15, 16, 17, 18, 19, 20],
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '15 / 16 / 17 / 18 / 19 / 20%',
      },
    ],
  },
  {
    description:
      'Additionally, <b>Udyr</b> grants himself a <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Shield"><a href="/wiki/Shield" title="Shield"><img alt="Hybrid resistances icon.png" src="/wiki/images/Hybrid_resistances_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Shield" title="Shield">shield</a></span> for 4 seconds.',
    leveling: [
      {
        effectType: 'Heal',
        name: 'Shield Strength:',
        raw: '45 / 60 / 75 / 90 / 105 / 120 (+ 40% AP) (+ 2 / 2.3 / 2.6 / 2.9 / 3.2 / 3.5% maximum health)',
        healType: 'BonusHealth',
        values: [45, 60, 75, 90, 105, 120],
        user: 'none',
        units: '',
        unitsText: '',
        pre: '45 / 60 / 75 / 90 / 105 / 120',
        children: [
          {
            values: 40,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 40% AP',
          },
          {
            values: [2, 2.3, 2.6, 2.9, 3.2, 3.5],
            valuesIsPercent: true,
            user: 'player',
            units: 'maximum_hp',
            unitsText: 'maximum health',
            pre: '+ 2 / 2.3 / 2.6 / 2.9 / 3.2 / 3.5% maximum health',
          },
        ],
      },
    ],
  },
  {
    description:
      '<span class="template_sbc"><b>Recast - Awaken:</b></span> <b>Udyr</b> increases the <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Shield"><a href="/wiki/Shield" title="Shield"><img alt="Hybrid resistances icon.png" src="/wiki/images/Hybrid_resistances_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Shield" title="Shield">shield\'s</a></span> strength, stacking with the remaining shield from the first cast, and <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Heal"><a href="/wiki/Healing" title="Healing"><img alt="Heal power icon.png" src="/wiki/images/Heal_power_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Healing" title="Healing">heals</a></span> every 0.<small>25</small> seconds over the next 4 seconds, as well as causes the empowered attacks to instead gain doubled <span style="white-space:nowrap"><a href="/wiki/Life_steal" title="Life steal"><img alt="Life steal icon.png" src="/wiki/images/Life_steal_icon.png" decoding="async" loading="lazy" width="15" height="15" class="lazyload"></a>&nbsp;<a href="/wiki/Life_steal" title="Life steal">life steal</a></span> and <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Heal"><a href="/wiki/Healing" title="Healing"><img alt="Heal power icon.png" src="/wiki/images/Heal_power_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Healing" title="Healing">heal</a></span> him for <span style="color: #1F995C; white-space:normal">2.<small>4</small>% of his <b>maximum</b> health</span> <span style="color: #7A6DFF; white-space:normal">(+&nbsp;16% AP)</span> on-hit.',
    leveling: [
      {
        effectType: 'Heal',
        name: 'Line 3:',
        raw: '4% of his maximum health (+ 16% AP) on-hit',
        healType: 'BonusHealth',
        values: 4,
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: 'on-hit',
        pre: '4% of his maximum health',
        post: 'on-hit',
        children: [
          {
            values: 16,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 16% AP',
          },
        ],
      },
      {
        effectType: 'Heal',
        name: 'Increased Shield Strength:',
        raw: '20 − 150 (based on level) (+ 45 / 60 / 75 / 90 / 105 / 120) (+ 65% AP) (+ 8% maximum health)',
        healType: 'BonusHealth',
        values: [
          20, 27.65, 35.29, 42.94, 50.59, 58.24, 65.88, 73.53, 81.18, 88.82,
          96.47, 104.12, 111.76, 119.41, 127.06, 134.71, 142.35, 150,
        ],
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '20 − 150',
        children: [
          {
            values: [45, 60, 75, 90, 105, 120],
            user: 'none',
            units: '',
            unitsText: '',
            pre: '+ 45 / 60 / 75 / 90 / 105 / 120',
          },
          {
            values: 65,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 65% AP',
          },
          {
            values: 8,
            valuesIsPercent: true,
            user: 'player',
            units: 'maximum_hp',
            unitsText: 'maximum health',
            pre: '+ 8% maximum health',
          },
        ],
      },
      {
        effectType: 'Heal',
        name: 'Total Healing:',
        raw: '10 − 75 (based on level) (+ 22.5 / 30 / 37.5 / 45 / 52.5 / 60) (+ 32.5% AP) (+ 4% maximum health)',
        healType: 'BonusHealth',
        values: [
          10, 13.82, 17.65, 21.47, 25.29, 29.12, 32.94, 36.76, 40.59, 44.41,
          48.24, 52.06, 55.88, 59.71, 63.53, 67.35, 71.18, 75,
        ],
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '10 − 75',
        children: [
          {
            values: [22.5, 30, 37.5, 45, 52.5, 60],
            user: 'none',
            units: '',
            unitsText: '',
            pre: '+ 22.5 / 30 / 37.5 / 45 / 52.5 / 60',
          },
          {
            values: 32.5,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 32.5% AP',
          },
          {
            values: 4,
            valuesIsPercent: true,
            user: 'player',
            units: 'maximum_hp',
            unitsText: 'maximum health',
            pre: '+ 4% maximum health',
          },
        ],
      },
      {
        effectType: 'Heal',
        name: 'Heal per Tick:',
        raw: '0.63 − 4.69 (based on level) (+ 1.41 / 1.88 / 2.34 / 2.81 / 3.28 / 3.75) (+ 2.03% AP) (+ 0.25% maximum health)',
        healType: 'BonusHealth',
        values: [
          0.63, 0.87, 1.11, 1.35, 1.59, 1.82, 2.06, 2.3, 2.54, 2.78, 3.02, 3.26,
          3.5, 3.73, 3.97, 4.21, 4.45, 4.69,
        ],
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '0.63 − 4.69',
        children: [
          {
            values: [1.41, 1.88, 2.34, 2.81, 3.28, 3.75],
            user: 'none',
            units: '',
            unitsText: '',
            pre: '+ 1.41 / 1.88 / 2.34 / 2.81 / 3.28 / 3.75',
          },
          {
            values: 2.03,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 2.03% AP',
          },
          {
            values: 0.25,
            valuesIsPercent: true,
            user: 'player',
            units: 'maximum_hp',
            unitsText: 'maximum health',
            pre: '+ 0.25% maximum health',
          },
        ],
      },
      {
        effectType: 'Unique',
        name: 'Increased Life Steal:',
        raw: '30 / 32 / 34 / 36 / 38 / 40%',
        values: [30, 32, 34, 36, 38, 40],
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '30 / 32 / 34 / 36 / 38 / 40%',
      },
    ],
  },
  {
    description:
      'Healing <a href="/wiki/On-hit" class="mw-redirect" title="On-hit">on-hit</a> is reduced to 60% against <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Minions"><a href="/wiki/Minion_(League_of_Legends)" title="Minion (League of Legends)"><img alt="Minion icon.png" src="/wiki/images/Minion_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Minion_(League_of_Legends)" title="Minion (League of Legends)">minions</a></span>.',
    leveling: [],
  },
];
const E: SubSkill[] = [
  {
    img: '/wiki/images/Udyr_Blazing_Stampede.png',
    description:
      '<span class="template_sbc"><b>Active - Stance:</b></span> <b>Udyr</b> enters <i>Stampede Stance</i>, empowering his basic attacks to have an <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Uncancellable windup"><a href="/wiki/Basic_attack#Uncancellable_Windup" title="Basic attack#Uncancellable Windup"><img alt="Relentless Force 2.png" src="/wiki/images/Vi_Relentless_Force_2.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Basic_attack#Uncancellable_Windup" title="Basic attack">uncancellable windup</a></span> and <span class="basic-tooltip" style="border-bottom:1px dotted gray;cursor:help;" title="to 75 units closer than attack range, if Udyr is not closer already (pending for test)"><span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Dash"><a href="/wiki/Dash" title="Dash"><img alt="Dash.png" src="/wiki/images/Dash.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Dash" title="Dash">pounce</a></span> on the target</span> to <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Stun"><a href="/wiki/Stun" title="Stun"><img alt="Stun icon.png" src="/wiki/images/Stun_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Stun" class="mw-redirect" title="Stun">stun</a></span> them for 0.<small>75</small> seconds. This cannot affect the same target more than once every few seconds.',
    leveling: [],
  },
  {
    description:
      'Additionally, <b>Udyr</b> becomes <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Ghosted"><a href="/wiki/Unit_collision" title="Unit collision"><img alt="Ghost.png" src="/wiki/images/Ghost.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Unit_collision" title="Unit collision">ghosted</a></span> and gains <span style="white-space:nowrap"><a href="/wiki/Movement_speed" title="Movement speed"><img alt="Movement speed icon.png" src="/wiki/images/Movement_speed_icon.png" decoding="async" loading="lazy" width="15" height="15" class="lazyload"></a>&nbsp;<span style="color: #F5EE99; white-space:normal"><b>bonus</b> movement speed</span></span> for 4 seconds, which decays to 30% effectiveness over 1.<small>5</small> seconds.',
    leveling: [
      {
        effectType: 'Unique',
        name: 'Bonus Movement Speed:',
        raw: '30 / 37 / 44 / 51 / 58 / 65%',
        values: [30, 37, 44, 51, 58, 65],
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '30 / 37 / 44 / 51 / 58 / 65%',
      },
      {
        effectType: 'Unique',
        name: 'Decayed Bonus Movement Speed:',
        raw: '9 / 11.1 / 13.2 / 15.3 / 17.4 / 19.5%',
        values: [9, 11.1, 13.2, 15.3, 17.4, 19.5],
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '9 / 11.1 / 13.2 / 15.3 / 17.4 / 19.5%',
      },
    ],
  },
  {
    description:
      '<span class="template_sbc"><b>Recast - Awaken:</b></span> <b>Udyr</b> gains <span style="white-space:nowrap"><a href="/wiki/Range" title="Range"><img alt="Range icon.png" src="/wiki/images/Range_icon.png" decoding="async" loading="lazy" width="15" height="15" class="lazyload"></a>&nbsp;75</span> <b>bonus</b> attack range and an additional <span style="color: #F5EE99; white-space:normal"><span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="30;" data-finish="40;" data-bot_values="30;30.59;31.18;31.76;32.35;32.94;33.53;34.12;34.71;35.29;35.88;36.47;37.06;37.65;38.24;38.82;39.41;40" data-top_values="" data-bot_key="%">30% − 40% (based on level)</span> <b>bonus</b> movement speed</span>. He also gains <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Cc-immune"><a href="/wiki/Crowd_control#Immunity" title="Crowd control#Immunity"><img alt="Cc-immune icon.png" src="/wiki/images/Cc-immune_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Crowd_control#Immunity" title="Crowd control">immunity to crowd control</a></span> for 1.<small>5</small> seconds.',
    leveling: [
      {
        effectType: 'Gain',
        name: 'Line 1:',
        raw: ' Udyr gains  75 bonus attack range and an additional 30% − 40% (based on level) bonus movement speed',
        values: [],
        valuesIsPercent: true,
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: 'bonus movement speed',
        pre: 'Udyr gains  75 bonus attack range and an additional 30% − 40%',
        post: 'bonus movement speed',
      },
    ],
  },
];
const R: SubSkill[] = [
  {
    img: '/wiki/images/Udyr_Wingborne_Storm.png',
    description:
      '<span class="template_sbc"><b>Active - Stance:</b></span> <b>Udyr</b> enters <i>Storm Stance</i>, empowering his next two basic attacks to deal <span style="color: #00B0F0; white-space:normal"><span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="10;" data-finish="30;" data-bot_values="10;11.18;12.35;13.53;14.71;15.88;17.06;18.24;19.41;20.59;21.76;22.94;24.12;25.29;26.47;27.65;28.82;30" data-top_values="">10 − 30 (based on level)</span></span> <span style="color: #7A6DFF; white-space:normal">(+&nbsp;30% AP)</span> <span style="color: #00B0F0; white-space:normal">magic damage</span> to nearby enemies.',
    leveling: [
      {
        effectType: 'Damage',
        name: 'Line 1:',
        raw: ' Udyr enters Storm Stance, empowering his next two basic attacks to deal 10 − 30 (based on level) (+ 30% AP) magic damage to nearby enemies',
        damagetype: 'Magic',
        values: [
          10, 11.18, 12.35, 13.53, 14.71, 15.88, 17.06, 18.24, 19.41, 20.59,
          21.76, 22.94, 24.12, 25.29, 26.47, 27.65, 28.82, 30,
        ],
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: 'magic damage to nearby enemies',
        pre: 'Udyr enters Storm Stance, empowering his next two basic attacks to deal 10 − 30',
        post: 'magic damage to nearby enemies',
        children: [
          {
            values: 30,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 30% AP',
          },
        ],
      },
    ],
  },
  {
    description:
      'Additionally, <b>Udyr</b> summons a blizzard around himself for 4 seconds that deals <span style="color: #00B0F0; white-space:normal">magic damage</span> every 0.<small>5</small> seconds to nearby enemies and <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Slow"><a href="/wiki/Slow" title="Slow"><img alt="Slow icon.png" src="/wiki/images/Slow_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Slow" class="mw-redirect" title="Slow">slows</a></span> them. <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Minions"><a href="/wiki/Minion_(League_of_Legends)" title="Minion (League of Legends)"><img alt="Minion icon.png" src="/wiki/images/Minion_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Minion_(League_of_Legends)" title="Minion (League of Legends)">Minions</a></span> take <span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="50;1" data-finish="80;16" data-bot_values="50;60;70;80" data-top_values="1;6;11;16" data-bot_key="%">50 / 60 / 70 / 80% (based on level)</span> damage.',
    leveling: [
      {
        effectType: 'Damage',
        name: 'Line 3:',
        raw: '  Minions take 50 / 60 / 70 / 80% (based on level) damage',
        damagetype: 'None',
        values: [],
        valuesIsPercent: true,
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: 'damage',
        pre: 'Minions take 50 / 60 / 70 / 80%',
        post: 'damage',
      },
      {
        effectType: 'Unique',
        name: 'Magic Damage per Tick:',
        raw: '10 / 19 / 28 / 37 / 46 / 55 (+ 17.5% AP)',
        values: [10, 19, 28, 37, 46, 55],
        user: 'none',
        units: '',
        unitsText: '',
        pre: '10 / 19 / 28 / 37 / 46 / 55',
        children: [
          {
            values: 17.5,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 17.5% AP',
          },
        ],
      },
      {
        effectType: 'Unique',
        name: 'Total Magic Damage:',
        raw: '80 / 152 / 224 / 296 / 368 / 440 (+ 140% AP)',
        values: [80, 152, 224, 296, 368, 440],
        user: 'none',
        units: '',
        unitsText: '',
        pre: '80 / 152 / 224 / 296 / 368 / 440',
        children: [
          {
            values: 140,
            valuesIsPercent: true,
            user: 'player',
            units: 'total_ap',
            unitsText: 'AP',
            pre: '+ 140% AP',
          },
        ],
      },
      {
        effectType: 'Unique',
        name: 'Slow:',
        raw: '15 / 18 / 21 / 24 / 27 / 30%',
        values: [15, 18, 21, 24, 27, 30],
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '15 / 18 / 21 / 24 / 27 / 30%',
      },
    ],
  },
  {
    description:
      '<span class="template_sbc"><b>Recast - Awaken:</b></span> <b>Udyr</b> ends the blizzard if it is active and unleashes a glacial storm for 4 seconds that is able to move on its own, as well as causes the empowered attacks to instead deal their damage to enemies within that storm. The storm follows the closest nearby <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Sight"><a href="/wiki/Sight" title="Sight"><img alt="Sight icon.png" src="/wiki/images/Sight_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Sight" title="Sight">visible</a></span> target and applies the same effects but deals <a href="/wiki/Critical_strike#Cosmetic_critical_strikes" title="Critical strike#Cosmetic critical strikes"><img alt="Critical strike magic icon.png" src="/wiki/images/Critical_strike_magic_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <span class="basic-tooltip" style="border-bottom:1px dotted gray;cursor:help;" title="Cosmetic critical strike"><span style="color: #00B0F0; white-space:normal"><b>bonus</b> magic damage</span></span> equal to<span id="container" class="container" style="cursor:help;"><span class="flipText1 active">「&nbsp;<span style="color: #1F995C; white-space:normal"><span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="1;" data-finish="2;" data-bot_values="1;1.06;1.12;1.18;1.24;1.29;1.35;1.41;1.47;1.53;1.59;1.65;1.71;1.76;1.82;1.88;1.94;2" data-top_values="" data-bot_key="%">1% − 2% (based on level)</span></span> <span style="color: #7A6DFF; white-space:normal">(+&nbsp;0.<small>4375</small>% per 100 AP)</span> <span style="color: #1F995C; white-space:normal">of the target\'s <b>maximum</b> health</span> per tick, capped at <span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="10;" data-finish="50;" data-bot_values="10;12.35;14.71;17.06;19.41;21.76;24.12;26.47;28.82;31.18;33.53;35.88;38.24;40.59;42.94;45.29;47.65;50" data-top_values="">10 − 50 (based on level)</span>&nbsp;」</span><span class="flipText2">「&nbsp;<span style="color: #1F995C; white-space:normal"><span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="8;" data-finish="16;" data-bot_values="8;8.47;8.94;9.41;9.88;10.35;10.82;11.29;11.76;12.24;12.71;13.18;13.65;14.12;14.59;15.06;15.53;16" data-top_values="" data-bot_key="%">8% − 16% (based on level)</span></span> <span style="color: #7A6DFF; white-space:normal">(+&nbsp;3.<small>5</small>% per 100 AP)</span> <span style="color: #1F995C; white-space:normal">of the target\'s <b>maximum</b> health</span> over the duration, capped at <span class="pp-tooltip" style="position:relative; border-bottom:1px dotted; cursor:help;" data-start="80;" data-finish="400;" data-bot_values="80;98.82;117.65;136.47;155.29;174.12;192.94;211.76;230.59;249.41;268.24;287.06;305.88;324.71;343.53;362.35;381.18;400" data-top_values="">80 − 400 (based on level)</span>&nbsp;」</span></span>against <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Monsters"><a href="/wiki/Monster" title="Monster"><img alt="Monster icon.png" src="/wiki/images/Monster_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Monster" title="Monster">monsters</a></span>, and <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Slow"><a href="/wiki/Slow" title="Slow"><img alt="Slow icon.png" src="/wiki/images/Slow_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Slow" class="mw-redirect" title="Slow">slows</a></span> by an additional 10%.',
    leveling: [
      {
        effectType: 'Damage',
        name: 'Line 2:',
        raw: ' The storm follows the closest nearby  visible target and applies the same effects but deals  bonus magic damage equal to「 1% − 2% (based on level) (+ 0',
        damagetype: 'Magic',
        values: [],
        valuesIsPercent: true,
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: '+ 0',
        pre: 'The storm follows the closest nearby  visible target and applies the same effects but deals  bonus magic damage equal to「 1% − 2%',
        post: '+ 0',
      },
      {
        effectType: 'Heal',
        name: 'Line 3:',
        raw: "4375% per 100 AP) of the target's maximum health per tick, capped at 10 − 50 (based on level) 」「 8% − 16% (based on level) (+ 3",
        healType: 'OutgoingHeals',
        values: [
          10, 12.35, 14.71, 17.06, 19.41, 21.76, 24.12, 26.47, 28.82, 31.18,
          33.53, 35.88, 38.24, 40.59, 42.94, 45.29, 47.65, 50,
        ],
        valuesIsPercent: true,
        valuesIsBasedOnLevel: true,
        user: 'none',
        units: '',
        unitsText: '」「 8% − 16%',
        pre: "4375% per 100 AP of the target's maximum health per tick, capped at 10 − 50",
        post: '」「 8% − 16%',
      },
      {
        effectType: 'Heal',
        name: 'Line 4:',
        raw: "5% per 100 AP) of the target's maximum health over the duration, capped at 80 − 400 (based on level) 」against  monsters, and  slows by an additional 10%",
        healType: 'OutgoingHeals',
        values: [
          80, 98.82, 117.65, 136.47, 155.29, 174.12, 192.94, 211.76, 230.59,
          249.41, 268.24, 287.06, 305.88, 324.71, 343.53, 362.35, 381.18, 400,
        ],
        valuesIsPercent: true,
        valuesIsBasedOnLevel: true,
        user: 'player',
        units: 'total_ad',
        unitsText: '」against  monsters, and  slows by an additional 10%',
        pre: "5% per 100 AP of the target's maximum health over the duration, capped at 80 − 400",
        post: '」against  monsters, and  slows by an additional 10%',
      },
      {
        effectType: 'Unique',
        name: 'Increased Slow:',
        raw: '25 / 28 / 31 / 34 / 37 / 40%',
        values: [25, 28, 31, 34, 37, 40],
        valuesIsPercent: true,
        user: 'none',
        units: '',
        unitsText: '',
        pre: '25 / 28 / 31 / 34 / 37 / 40%',
      },
    ],
  },
  {
    description:
      'The unleashed storm grants <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Sight"><a href="/wiki/Sight" title="Sight"><img alt="Sight icon.png" src="/wiki/images/Sight_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Sight" title="Sight">sight</a></span> of its <span class="basic-tooltip" style="border-bottom:1px dotted gray;cursor:help;" title="Does not permeate through terrain or brush">surroundings</span> and prioritizes following the last enemy <b>Udyr</b> has attacked while he is nearby, then enemy <span class="glossary" style="white-space:pre; position:relative;" data-game="lol" data-tip="Champions"><a href="/wiki/Champion" title="Champion"><img alt="Champion icon.png" src="/wiki/images/Champion_icon.png" decoding="async" loading="lazy" width="20" height="20" class="lazyload"></a> <a href="/wiki/Champion" title="Champion">champions</a></span>, then non-champions, then <b>Udyr</b>.',
    leveling: [],
  },
];
export const Udyr = { I, Q, W, E, R };
